### ISSUE TITLE
Pkg-config package has hardcoded ELPA version

### ISSUE THREAD

**Issue by jhrmnn** [conda-forge/elsi-feedstock#12]
```
$ cat $CONDA_PREFIX/lib/pkgconfig/elsi.pc
prefix=/Users/jhermann/Library/Caches/conda/envs/libmbd
libdir=/Users/jhermann/Library/Caches/conda/envs/libmbd/lib
includedir=/Users/jhermann/Library/Caches/conda/envs/libmbd/include

Name: elsi
Description: Electronic structure infrastructure
Version: 2.8.2
URL: http://elsi-interchange.org

Libs: -L${libdir} -L-L/Users/jhermann/Library/Caches/conda/envs/libmbd/lib -L-L/Users/jhermann/Library/Caches/conda/envs/libmbd/lib -lelsi -lfortjson -lelpa_openmp -lscalapack -llapack -lblas -lNTPoly -lOMM -lMatrixSwitch -lscalapack -llapack -lblas
Cflags: -I${includedir} -I/Users/jhermann/Library/Caches/conda/envs/libmbd/include/elpa_openmp-2021.05.002 -I/Users/jhermann/Library/Caches/conda/envs/libmbd/include/elpa_openmp-2021.05.002/modules -I/Users/jhermann/Library/Caches/conda/envs/libmbd/include
```
This stopped working now that ELPA 2021.11 was released on Conda-forge.

**Comment by awvwgk** [comment]
Thanks for bringing this up. I think rebuilding ELSI should fix this for now (and maybe pin ELPA to the exact version), however I should patch the ELPA feedstock to remove the version number completely.

It would be much easier if ELSI's pkg-config could just use a `Require: elpa_openmp` instead of reexporting all the flags...

**Comment by awvwgk** [comment]
Made a rebuild, now we should be fine, but we have to still have to patch ELPA.

**Comment by jhrmnn** [comment]
Thanks, Libmbd's CI passes now.

Btw I set up a regular weekly run of the CI for Libmbd to catch things like these, and apparently it's useful.

**Comment by awvwgk** [comment]
Will try to patch this behaviour in https://github.com/conda-forge/elpa-feedstock/pull/13, might require to rebuild ELSI (again).

**Comment by awvwgk** [comment]
Sorry for breaking libmbd again, I'll rebuild in https://github.com/conda-forge/elsi-feedstock/pull/14 and we might have to rebuild libmbd as well.

Going forward I'll look into creating a migrator for ELPA to do this automatically, rather than by hand.
