### ISSUE TITLE
Dependency pinning question

### ISSUE THREAD

**Issue by aradi** [conda-forge/elsi-feedstock#18]
### Comment:

A quick question, as I am not 100% familiar with dependency pinning and the `pin_subpackage()` directive (I find the corresponding Conda docs rather confusing....). Does
```
build:
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }} {{ mpi_prefix }}_*
```
ensure, that all dependencies (especially libomm, matrixswitch, elpa and ntpoly) are pinned in their major and minor versions? Elsi 2.8.* is broken on Conda (it did not have this `pin_subpackage` option),  because it pulls now NTPoly 3.0 (instead of 2.9), which has incompatible changes. I just wish to get confirmed, that using the option above this can not happen again. (Is this equivalent to adding individual `pin_compatible()` settings in the `run` section for each of those components?)

**Comment by awvwgk** [comment]
There is a run export for the version pin in NTPoly, so this should not happen. One option is to be explicit in ELSI and add an additional pinning here.

**Comment by aradi** [comment]
Thanks for the quick answer, I understand it somewhat better now. But then, it is probably more robust to add those pinnings explicitly here and not rely on the subpackages. (I'll do that accordingly in my upgrade PR #19)
